baseURL = "https://conjectureguy.github.io/"
languageCode = 'en-us'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about/"
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "posts/"


[params]
user = "conjectureguy"
hostname = "github.io"
  [params.author]
    name = "Rahul R Katarki"  # Website and RSS feed author
    email = "katarki.rahul@gmail.com"  # RSS feed email address


readingTime = false  # Show reading time on post page
published = false  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/conjectureguy"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 2
name = "codeforces"
url = "https://codeforces.com/profile/conjectureguy"
aria = "Codeforces Profile"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/rahulrkatarki/"
aria = "Codeforces Profile"

[[params.social]]
key = 3
name = "email"
url = "mailto:katarki.rahul@gmail.com"
aria = "My e-Mail Address"